const dummyData = [
    { title: '1', content: '1번째 포켓몬', type: '풀' },
    { title: '2', content: '2번째 포켓몬', type: '불꽃' },
    { title: '3', content: '3번째 포켓몬', type: '물' },
    { title: '4', content: '4번째 포켓몬', type: '전기' },
    { title: '5', content: '5번째 포켓몬', type: '페어리' },
    { title: '6', content: '6번째 포켓몬', type: '강철' },
    { title: '7', content: '7번째 포켓몬', type: '바위' },
    { title: '8', content: '8번째 포켓몬', type: '어둠' },
    { title: '9', content: '9번째 포켓몬', type: '격투' },
    { title: '10', content: '10번째 포켓몬', type: '독' },
    { title: '11', content: '11번째 포켓몬', type: '땅' },
    { title: '12', content: '12번째 포켓몬', type: '얼음' },
    { title: '13', content: '13번째 포켓몬', type: '빛' },
    { title: '14', content: '14번째 포켓몬', type: '물' },
    { title: '15', content: '15번째 포켓몬', type: '불꽃' },
    { title: '16', content: '16번째 포켓몬', type: '전기' },
    { title: '17', content: '17번째 포켓몬', type: '바위' },
    { title: '18', content: '18번째 포켓몬', type: '풀' },
    { title: '19', content: '19번째 포켓몬', type: '어둠' },
    { title: '20', content: '20번째 포켓몬', type: '페어리' },
    { title: '21', content: '21번째 포켓몬', type: '독' },
    { title: '22', content: '22번째 포켓몬', type: '격투' },
    { title: '23', content: '23번째 포켓몬', type: '빛' },
  ];
  
  export default dummyData;